# based on this
# https://gist.github.com/dan-blanchard/7045057
language: python
sudo: false
python:
  - 2.7
#  - 3.3
notifications:
  email: false

# Setup anaconda
before_install:
# python 3 needs something different    
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
# Install packages
install:
  - conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION pip nose numpy cython scipy nose
  # can we make this optional?
  - conda install --yes -n test_env -c mforbes pyfftw
  - source activate test_env
  - python setup.py build_ext --inplace
  - python setup.py install

# Run test
script:
#  - nosetests --with-cov --cov YOUR_PACKAGE_NAME_HERE --cov-config .coveragerc --logging-level=INFO
#  - python setup.py test
  - nosetests
# Calculate coverage
#after_success:
#  - coveralls --config_file .coveragerc